config/routes.rb
Ticketee::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }

  get '/awaiting_confirmation',
    :to => "users#confirmation",
    :as => 'confirm_user'

  resources :projects do
    resources :tickets
  end

  namespace :admin do
    root :to => "base#index"
    resources :users
  end
  
  namespace :api do
    namespace :v1 do
      resources :projects
    end
  end

  root :to => 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, :presence => true
  has_many :tickets, :dependent => :delete_all
  has_many :permissions, :as => :thing
  
  scope :readable_by, lambda { |user|
    joins(:permissions).where(:permissions => { :user_id => user.id,
                                                :action => 'view'
                                              } )
  }
  
  attr_accessible :name
  
  def self.for(user)
    user.admin? ? Project : Project.readable_by(user)
  end
  
  def last_ticket
    tickets.last
  end
end

app/controllers/api/v1/projects_controller.rb
class Api::V1::ProjectsController < Api::V1::BaseController
  before_filter :authorize_admin!, :except => [:index, :show]
  before_filter :find_project, :only => [:show, :update, :destroy]
  
  def index
    respond_with Project.for(current_user).all
  end
  
  def create
    project = Project.create(params[:project])
    if project.valid?
      respond_with(project, :location => api_v1_project_path(project))
    else
      respond_with project
    end
  end
  
  def show
    respond_with @project, :methods => 'last_ticket'
  end
  
  def update
    @project.update_attributes(params[:project])
    respond_with @project
  end
  
  def destroy
    @project.destroy
    respond_with @project
  end
  
  private
  
  def find_project
    @project = Project.for(current_user).find(params[:id])
  rescue ActiveRecord::RecordNotFound
    error = {:error => "The project you are looking for cannot be found." }
    respond_with error, :status => 404 
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authorize_admin!, :except => [:index, :show]
  before_filter :authenticate_user!, :only => [:index, :show]
  before_filter :find_project, :only => [:show, :edit, :update, :destroy]
  
  def index
    @projects = Project.for(current_user).all
  end
  
  def new
    @project = Project.new
  end
  
  def create
    @project = Project.new(params[:project])
    if @project.save
      redirect_to @project, :notice => "Project has been created"
    else
      flash[:alert] = "Project has not been created"
      render 'new'
    end
  end
  
  def update
    if @project.update_attributes(params[:project])
      flash[:notice] = "Project has been updated."
      redirect_to @project
    else
      flash[:alert] = "Project has not been updated."
      render 'edit'
    end
  end
  
  def destroy
    @project.delete
    redirect_to projects_path, :notice => "Project has been deleted."
  end
  
  private
  
  def find_project
    @project = Project.for(current_user).find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The project you were looking for could not be found."
    redirect_to projects_path
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << 'Ticketee').join(' - ')
      end
    end
  end
  
  def admins_only(&block)
    block.call if current_user.try(:admin?)
  end
  
end

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <%= f.error_messages %>
  <p>
  	<%= f.label :name, 'Project name' %>
  	<%= f.text_field :name %>
  </p>
  <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h2>Edit page</h2>
<%= render 'form' %>

app/views/projects/index.html.erb
<% admins_only do %>
  <%= link_to 'New Project', new_project_path %>
<% end %>

<h2>Projects</h2>
<ul>
  <% @projects.each do |project| %>
    <li><%= link_to project.name, project %></li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<h1>New Project</h1>
<%= render 'form' %>

app/views/projects/show.html.erb
<%= title @project.name, 'Projects' %>
<%= @project.name %>
<% admins_only do %>
  <%= link_to "Edit Project", edit_project_path(@project) %>
  <%= link_to "Delete Project", @project, :method => :delete %>
<% end %>

<% authorized?('create tickets', @project) do %>
  <%= link_to "New Ticket", new_project_ticket_path(@project) %>
<% end %>

<ul id='tickets'>
  <% @project.tickets.each do |ticket| %>
    <li>
      #<%= ticket.id %> - <%= link_to ticket.title, [@project, ticket] %>
    </li>
  <% end %>
</ul>